# Generated by Django 4.2.5 on 2023-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_image_multipleimages_delete_testimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='IMG/')),
            ],
        ),
        migrations.RemoveField(
            model_name='multipleimages',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='MultipleImages',
        ),
    ]
