# Generated by Django 4.2.5 on 2023-10-13 08:50

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_img_remove_multipleimages_images_delete_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.product_image_upload_to),
        ),
    ]
