# Generated by Django 4.2.5 on 2023-10-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UkrPostShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('index', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ukr_shipping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewPostShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_delivery', models.CharField(choices=[('department', 'Доставка у відділення "Нової Пошти"'), ('address', 'Доставка за адресою'), ('np_post_box', 'Доставка у поштомат "Нової Пошти"')], default='department', max_length=50)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('department_address', models.TextField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('np_post_box', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='np_shipping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
